<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo CF_INSTANCE_NAME; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="CF-Manager 2">
    <meta name="author" content="Diftraku">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="css/jquery.growl.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50">
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#/"><?php echo CF_INSTANCE_NAME; ?></a>
            </div>
            <div class="navbar-collapse collapse" id="menu"></div>
        </div>
    </nav>
</header>
<div id="content" class="container-fluid"></div>

<!--<script data-main="app/config/config" src="app/lib/require.js"></script>-->
<script src="app/lib/require.js"></script>
<script type="text/javascript">
    window.CFUser = {id: 0, username: 'system', email: 'system@localhost.localdomain', gravatar: '', name: 'System User', logged_in: true};
    window.CFMeta = {types: {1: {label: 'Ticket', price: 0.00, shirts: [false, false]}}, states: {1: {label: 'Open', description: 'Open ticket'}}};
    if (window.require) {
        // Init and load User model
        require(['app/config/config.js'], function (_) {
            console.log('CF-Manager 2 v<?php echo CF_VERSION; ?>');
        });
    }
</script>
</body>
</html>
